<?xml version="1.0" ?>
<robot xmlns:xacro ="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find chapt6_rob_descrip)/urdf/fishbot/common_inertia.urdf.xacro"/>

    <xacro:macro name="base_xacro" params="length radius">
        <link name="base_footprint"/>

        <joint name="base_footprint2base_link" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
        </joint>
        
        <link name="base_link"> 
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.6" />
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.6" />
                </material>
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
        </link>

    </xacro:macro>

</robot>